### ISSUE TITLE
Conflict with the subfigure package

### ISSUE THREAD

**Issue by bsamadi** [gioele/fixmetodonotes#15]
The following error disappears when I remove the subfigure package:

! LaTeX Error: Command \c@lofdepth already defined.
               Or name \end... illegal, see p.192 of the manual.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

l.99 \newcounter{lofdepth}

**Comment by gioele** [comment]
You stumbled on a known bug of subfigure, see http://tex.stackexchange.com/a/56803/11990.

Quoting from the answer:

> The error you are getting comes from loading the tocloft and subfigure packages simultaneously,
> […]
> By the way, sufigure is an obsolete package and shouldn't be used anymore; subfig or subcaption are valid alternatives

A quick & dirtyworkaround is to load `fixmetodonotes` using this code

```
\usepackage{subfigure}
\PassOptionsToPackage{subfigure}{tocloft}
\usepackage{fixmetodonotes}
```

**Comment by firminoazevedo** [comment]
\makeatletter
\let\c@lofdepth\relax
\let\c@lotdepth\relax
\makeatother
\usepackage{subfigure}

Eu consegui usando esses comandos
